server:
  port: 8083
  servlet:
    context-path: /
    
spring:
  application:
    name: menu-service

  datasource:
    url: jdbc:h2:mem:restaurantMenu;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true         # Habilita la consola web
      path: /h2-console     # URL para acceder a la consola

  jpa:
    hibernate:
      ddl-auto: update              # Crea o actualiza tablas según las entidades
    show-sql: true                  # Muestra las consultas SQL en la consola
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        #default_schema: menu        # Define el esquema por defecto

  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html