server:
  port: 8085
  servlet:
    context-path: /
    
spring:
  application:
    name: promotions-service

  datasource:
    url: jdbc:h2:mem:testdb  # Base de datos en memoria
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true         # Habilita la consola web
      path: /h2-console     # URL para acceder a la consola

  jpa:
    hibernate:
      ddl-auto: update      # Crea o actualiza tablas según las entidades
    show-sql: true          # Muestra las consultas SQL en la consola
    database-platform: org.hibernate.dialect.H2Dialect
