server:
  port: 8086
  servlet:
    context-path: /

spring:
  application:
    name: kafka-common-service

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      retries: 5
      batch-size: 4096
      buffer-memory: 1048576
      linger-ms: 1
      acks: all
      enable-idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

